window.dictyLabs = [
  { pi: "Stephen Alexander", institution: "University of Missouri", location: "Columbia, USA", url: "https://alexander.biology.missouri.edu/people/stephen-alexander/" },
  { pi: "Caroline Barisch", institution: "University of Osnabrück", location: "Osnabrück, Germany", url: "https://www.barischlabuos.com/" },
  { pi: "Ramamurthy Baskar", institution: "IIT Madras", location: "Chennai, India", url: "https://biotech.iitm.ac.in/Faculty/RB%20Lab/rb.html" },
  { pi: "Carsten Beta", institution: "University of Potsdam", location: "Potsdam, Germany", url: "https://www.uni-potsdam.de/en/biophysik/reseach/overview.html" },
  { pi: "Brenda Blacklock", institution: "Purdue School of Science", location: "Indianapolis, USA", url: "https://science.iupui.edu/people-directory/people/blacklock-brenda.html" },
  { pi: "Gareth Bloomfield", institution: "MRC Laboratory of Molecular Biology", location: "Cambridge, UK", url: "https://gareths.space/" },
  { pi: "Salvo Bozzaro", institution: "University of Turin", location: "Turin, Italy", url: "https://www.dscb.unito.it/do/gruppi.pl/Show?_id=rq0i", emeritus: true },
  { pi: "Derrick Brazill", institution: "Hunter College", location: "New York, USA", url: "https://www.huntercollegebrazilllab.com/" },
  { pi: "Huaqing Cai", institution: "Institute of Biophysics, Chinese Academy of Sciences", location: "Beijing, China", url: "http://www.ibp.cas.cn/sourcedb_ibp_cas/cn/ibpexport/swdfzgjzdsys/201912/t20191202_5447305.html" },
  { pi: "Pascale Charest", institution: "University of Arizona", location: "Tucson, USA", url: "https://www.thecharestlab.org/" },
  { pi: "Steve Charette", institution: "Université Laval", location: "Québec, Canada", url: "http://www.amibe.org/" },
  { pi: "Jonathan Chubb", institution: "UCL London", location: "London, UK", url: "https://www.ucl.ac.uk/lmcb/users/jonathan-chubb" },
  { pi: "Chang Chung", institution: "Vanderbilt University", location: "Nashville, USA", url: "https://labnodes.vanderbilt.edu/member/profile/id/11209" },
  { pi: "Pierre Cosson", institution: "University of Geneva", location: "Geneva, Switzerland", url: "https://www.ige3.unige.ch/cosson.php" },
  { pi: "Aline da Silva", institution: "University of São Paulo", location: "São Paulo, Brazil", url: "http://www3.iq.usp.br/pessoas_view.php?idDocente=4" },
  { pi: "Cynthia Damer", institution: "Central Michigan University", location: "Mount Pleasant, USA", url: "https://www.cmich.edu/colleges/se/biology/fac_staff/Pages/Cynthia-K.-Damer.aspx" },
  { pi: "Arturo DeLozanne", institution: "University of Texas at Austin", location: "Austin, USA", url: "http://www.zo.utexas.edu/faculty/delozanne/adlab.html" },
  { pi: "Peter Devreotes", institution: "Johns Hopkins University", location: "Baltimore, USA", url: "http://devreotes.johnshopkins.edu/" },
  { pi: "Robert Dottin", institution: "Hunter College", location: "New York, USA", url: "" },
  { pi: "Danton O'Day", institution: "University of Toronto at Mississauga", location: "Mississauga, Canada", url: "http://anakin.utm.utoronto.ca/~w3oday/" },
  { pi: "Ludwig Eichinger", institution: "University of Cologne", location: "Cologne, Germany", url: "http://www.uni-koeln.de/med-fak/biochemie/cellular_homeostasis/" },
  { pi: "Ricardo Escalante", institution: "Instituto de Investigaciones Biomedicas", location: "Madrid, Spain", url: "http://www2.iib.uam.es/rescalante_lab/Sitio_web/Escalante_Lab.html" },
  { pi: "Richard Firtel", institution: "UC San Diego", location: "San Diego, USA", url: "http://biology.ucsd.edu/research/faculty/rafirtel" },
  { pi: "Paul Fisher", institution: "La Trobe University", location: "Victoria, Australia", url: "https://scholars.latrobe.edu.au/display/prfisher" },
  { pi: "Carl Franck", institution: "Cornell University", location: "Ithaca, USA", url: "https://franckgroup.lassp.cornell.edu/" },
  { pi: "Günther Gerisch", institution: "Max Planck Institute of Biochemistry", location: "Martinsried, Germany", url: "http://www.biochem.mpg.de/gerisch/", emeritus: true },
  { pi: "Pierre Golstein", institution: "Centre d'Immunologie de Marseille-Luminy", location: "Marseille, France", url: "http://www.ciml.univ-mrs.fr/science/lab-pierre-golstein/molecular-mechanisms-cell-death" },
  { pi: "Richard Gomer", institution: "Texas A&M University", location: "College Station, USA", url: "https://www.bio.tamu.edu/lab-website-richard-gomer/" },
  { pi: "Eric Greer", institution: "Boston Children's Hospital / Harvard Medical School", location: "Boston, USA", url: "http://thegreerlab.com/" },
  { pi: "Jeffrey Hadwiger", institution: "Oklahoma State University", location: "Stillwater, USA", url: "https://microbiology.okstate.edu/faculty/hadwige/" },
  { pi: "Christian Hammann", institution: "Jacobs University", location: "Bremen, Germany", url: "https://www.jacobs-university.de/directory/hammann" },
  { pi: "Adrian Harwood", institution: "Cardiff University", location: "Cardiff, UK", url: "https://www.cardiff.ac.uk/people/view/58043-harwood-adrian" },
  { pi: "Falk Hillmann", institution: "Hans-Knöll-Institut", location: "Jena, Germany", url: "https://www.leibniz-hki.de/en/institut-staff-details.html?member=12" },
  { pi: "Robert Huber", institution: "Trent University", location: "Peterborough, Canada", url: "http://www.huberlab.ca/" },
  { pi: "Miho Iijima", institution: "Johns Hopkins University School of Medicine", location: "Baltimore, USA", url: "https://www.iijima-sesaki-lab.com/" },
  { pi: "Robert Insall", institution: "Institute for Cancer Sciences, Glasgow University", location: "Glasgow, UK", url: "https://www.gla.ac.uk/researchinstitutes/cancersciences/research/units/bicr/rinsall/" },
  { pi: "Chris Janetopoulos", institution: "University of the Sciences", location: "Philadelphia, USA", url: "https://faculty.usciences.edu/faculty/janetopoulos-christopher" },
  { pi: "Tian Jin", institution: "National Institutes of Health", location: "Bethesda, USA", url: "https://www.niaid.nih.gov/research/tian-jin-phd" },
  { pi: "Rob Kay", institution: "MRC Laboratory of Molecular Biology", location: "Cambridge, UK", url: "https://www2.mrc-lmb.cam.ac.uk/groups/rrk/research.php", emeritus: true },
  { pi: "Richard Kessin", institution: "Columbia University", location: "New York, USA", url: "https://sps.columbia.edu/faculty/richard-kessin", emeritus: true },
  { pi: "Alan Kimmel", institution: "National Institutes of Health", location: "Bethesda, USA", url: "https://www.niddk.nih.gov/about-niddk/staff-directory/biography/kimmel-alan" },
  { pi: "Jason King", institution: "University of Sheffield", location: "Sheffield, UK", url: "http://king.group.shef.ac.uk/" },
  { pi: "David Knecht", institution: "University of Connecticut", location: "Storrs, USA", url: "https://mcb.uconn.edu/person/david-knecht/" },
  { pi: "Edward Korn", institution: "National Institutes of Health", location: "Bethesda, USA", url: "https://www.nhlbi.nih.gov/node/84289", emeritus: true },
  { pi: "Arjan Kortholt & Peter van Haastert", institution: "University of Groningen", location: "Groningen, Netherlands", url: "https://www.rug.nl/research/cell-biochemistry/staff" },
  { pi: "Scot Kuo", institution: "Johns Hopkins University", location: "Baltimore, USA", url: "http://www.jhu.edu/cmml/" },
  { pi: "Kei Inouye", institution: "Kyoto University", location: "Kyoto, Japan", url: "http://cosmos.bot.kyoto-u.ac.jp/csm/index.html" },
  { pi: "Tera Levin", institution: "University of Pittsburgh", location: "Pittsburgh, USA", url: "https://www.teralevinlab.com/" },
  { pi: "Markus Maniak", institution: "Kassel University", location: "Kassel, Germany", url: "http://www.uni-kassel.de/fb10/institute/biologie/fachgebiete/zellbiologie/forschung.html" },
  { pi: "Dietmar Manstein", institution: "Hannover Medical School", location: "Hannover, Germany", url: "" },
  { pi: "Stanley Mauldin", institution: "Holy Family University", location: "Philadelphia, USA", url: "https://www.holyfamily.edu/school-of-arts-sciences-faculty/378-stanley-mauldin" },
  { pi: "Annette Mueller-Taubenberger", institution: "Ludwig Maximilians University", location: "Munich, Germany", url: "https://www.en.bmc.med.uni-muenchen.de/research/research_areas/principal_investigators/mueller-taubenbergera/index.html" },
  { pi: "Rupert Mutzel", institution: "Free University of Berlin", location: "Berlin, Germany", url: "http://www.biologie.fu-berlin.de/arbeitsgruppen/mikrobiologie/ag_mutzel/index.html" },
  { pi: "Vidya Nanjundiah", institution: "Indian Institute of Science", location: "Bangalore, India", url: "http://www.chg.res.in/Vidyanand.html", emeritus: true },
  { pi: "Suegene Noh", institution: "Colby College", location: "Waterville, USA", url: "" },
  { pi: "Kari Naylor", institution: "University of Central Arkansas", location: "Conway, USA", url: "" },
  { pi: "Justin Pachebat", institution: "Aberystwyth University", location: "Aberystwyth, UK", url: "https://www.aber.ac.uk/en/ibers/staff-profiles/listing/profile/jip/" },
  { pi: "Carole Parent", institution: "University of Michigan", location: "Ann Arbor, USA", url: "https://www.lsi.umich.edu/science/our-labs/carole-parent-lab" },
  { pi: "Young Shik Park", institution: "Inje University", location: "Kimhae, Korea", url: "http://home.inje.ac.kr/~biochemi/" },
  { pi: "Catherine Pears", institution: "Oxford University", location: "Oxford, UK", url: "" },
  { pi: "Barbara Pergolizzi", institution: "University of Turin", location: "Turin, Italy", url: "" },
  { pi: "Stefan Pukatzki", institution: "University of Alberta", location: "Edmonton, Canada", url: "" },
  { pi: "David Ratner", institution: "Amherst College", location: "Amherst, USA", url: "https://www.amherst.edu/people/facstaff/diratner", emeritus: true },
  { pi: "Francisco Rivero", institution: "University of Hull", location: "Hull, UK", url: "" },
  { pi: "Douglas Robinson", institution: "Johns Hopkins University School of Medicine", location: "Baltimore, USA", url: "" },
  { pi: "Matt Scaglione", institution: "Duke University School of Medicine", location: "Durham, USA", url: "" },
  { pi: "Pauline Schaap", institution: "University of Dundee", location: "Dundee, Scotland", url: "" },
  { pi: "Jeff Segall", institution: "Albert Einstein College of Medicine", location: "Bronx, USA", url: "" },
  { pi: "Gad Shaulsky", institution: "Baylor College of Medicine", location: "Houston, USA", url: "" },
  { pi: "Longfei Shu", institution: "Sun Yat-sen University", location: "Guangzhou, China", url: "" },
  { pi: "Charles Singleton", institution: "Vanderbilt University", location: "Nashville, USA", url: "", emeritus: true },
  { pi: "Fredrik Söderbom", institution: "University of Uppsala", location: "Uppsala, Sweden", url: "" },
  { pi: "Thierry Soldati", institution: "University of Geneva", location: "Geneva, Switzerland", url: "" },
  { pi: "David Soll", institution: "University of Iowa", location: "Iowa City, USA", url: "" },
  { pi: "Glaucia Souza", institution: "University of São Paulo", location: "São Paulo, Brazil", url: "" },
  { pi: "Pierre Stallforth", institution: "Hans Knöll Institut", location: "Jena, Germany", url: "" },
  { pi: "Paul Steimle", institution: "University of North Carolina at Greensboro", location: "Greensboro, USA", url: "" },
  { pi: "Joan Strassmann & David Queller", institution: "Washington University in St. Louis", location: "St. Louis, USA", url: "" },
  { pi: "Christopher Thompson", institution: "University College London", location: "London, UK", url: "https://thethompsonlab.wordpress.com/" },
  { pi: "Elinor Thompson", institution: "University of Greenwich", location: "Greenwich, UK", url: "" },
  { pi: "Igor Weber", institution: "Ruđer Bošković Institute", location: "Zagreb, Croatia", url: "" },
  { pi: "Gerald Weeks", institution: "University of British Columbia", location: "Vancouver, Canada", url: "", emeritus: true },
  { pi: "Cornelius Weijer", institution: "University of Dundee", location: "Dundee, Scotland", url: "" },
  { pi: "Christopher West", institution: "University of Georgia", location: "Athens, USA", url: "" },
  { pi: "Claire Wilhelm", institution: "Université Paris", location: "Paris, France", url: "" },
  { pi: "Jeffrey Williams", institution: "University of Dundee", location: "Dundee, Scotland", url: "" },
  { pi: "Robin Williams", institution: "Royal Holloway University of London", location: "London, UK", url: "" },
  { pi: "Thomas Winckler", institution: "Jena University", location: "Jena, Germany", url: "" },
];
