window.dictyLabs = [
  { pi: "Stephen Alexander", institution: "University of Missouri", location: "Columbia, USA", url: "", email: "alexanderst@missouri.edu" },
  { pi: "Caroline Barisch", institution: "University of Osnabrück", location: "Osnabrück, Germany", url: "", email: "Caroline.Barisch@uos.de" },
  { pi: "Ramamurthy Baskar", institution: "IIT Madras", location: "Chennai, India", url: "", email: "rbaskar@iitm.ac.in" },
  { pi: "Carsten Beta", institution: "University of Potsdam", location: "Potsdam, Germany", url: "https://www.uni-potsdam.de/en/biophysik/reseach/overview.html", email: "carsten.beta@uni-potsdam.de" },
  { pi: "Brenda Blacklock", institution: "Purdue School of Science", location: "Indianapolis, USA", url: "https://science.iupui.edu/people-directory/people/blacklock-brenda.html", email: "bblacklo@iupui.edu" },
  { pi: "Gareth Bloomfield", institution: "MRC Laboratory of Molecular Biology", location: "Cambridge, UK", url: "https://gareths.space/" },
  { pi: "Salvo Bozzaro", institution: "University of Turin", location: "Turin, Italy", url: "https://www.dscb.unito.it/do/gruppi.pl/Show?_id=rq0i", emeritus: true, email: "salvatore.bozzaro@unito.it" },
  { pi: "Derrick Brazill", institution: "Hunter College", location: "New York, USA", url: "", email: "brazill@genectr.hunter.cuny.edu" },
  { pi: "Huaqing Cai", institution: "Institute of Biophysics, Chinese Academy of Sciences", location: "Beijing, China", url: "", email: "huaqingcai@ibp.ac.cn" },
  { pi: "Pascale Charest", institution: "University of Arizona", location: "Tucson, USA", url: "https://www.thecharestlab.org/", email: "pcharest@arizona.edu" },
  { pi: "Steve Charette", institution: "Université Laval", location: "Québec, Canada", url: "http://www.amibe.org/", email: "Steve.Charette@bcm.ulaval.ca" },
  { pi: "Jonathan Chubb", institution: "UCL London", location: "London, UK", url: "https://www.ucl.ac.uk/lmcb/users/jonathan-chubb", email: "j.chubb@ucl.ac.uk" },
  { pi: "Chang Chung", institution: "Vanderbilt University", location: "Nashville, USA", url: "" },
  { pi: "Pierre Cosson", institution: "University of Geneva", location: "Geneva, Switzerland", url: "", email: "pierre.cosson@unige.ch" },
  { pi: "Aline da Silva", institution: "University of São Paulo", location: "São Paulo, Brazil", url: "" },
  { pi: "Cynthia Damer", institution: "Central Michigan University", location: "Mount Pleasant, USA", url: "", email: "damer1ck@cmich.edu" },
  { pi: "Arturo DeLozanne", institution: "University of Texas at Austin", location: "Austin, USA", url: "http://www.zo.utexas.edu/faculty/delozanne/adlab.html", email: "a.delozanne@utexas.edu" },
  { pi: "Peter Devreotes", institution: "Johns Hopkins University", location: "Baltimore, USA", url: "http://devreotes.johnshopkins.edu/", email: "pnd@jhmi.edu" },
  { pi: "Robert Dottin", institution: "Hunter College", location: "New York, USA", url: "", email: "dottin@genectr.hunter.cuny.edu" },
  { pi: "Danton O'Day", institution: "University of Toronto at Mississauga", location: "Mississauga, Canada", url: "", email: "danton.oday@utoronto.ca" },
  { pi: "Ludwig Eichinger", institution: "University of Cologne", location: "Cologne, Germany", url: "", email: "ludwig.eichinger@uni-koeln.de" },
  { pi: "Ricardo Escalante", institution: "Instituto de Investigaciones Biomedicas", location: "Madrid, Spain", url: "http://www2.iib.uam.es/rescalante_lab/Sitio_web/Escalante_Lab.html", email: "rescalante@iib.uam.es" },
  { pi: "Richard Firtel", institution: "UC San Diego", location: "San Diego, USA", url: "http://biology.ucsd.edu/research/faculty/rafirtel", email: "rafirtel@ucsd.edu" },
  { pi: "Paul Fisher", institution: "La Trobe University", location: "Victoria, Australia", url: "https://scholars.latrobe.edu.au/display/prfisher", email: "P.Fisher@latrobe.edu.au" },
  { pi: "Carl Franck", institution: "Cornell University", location: "Ithaca, USA", url: "https://franckgroup.lassp.cornell.edu/", email: "cpf1@cornell.edu" },
  { pi: "Günther Gerisch", institution: "Max Planck Institute of Biochemistry", location: "Martinsried, Germany", url: "http://www.biochem.mpg.de/gerisch/", emeritus: true },
  { pi: "Pierre Golstein", institution: "Centre d'Immunologie de Marseille-Luminy", location: "Marseille, France", url: "", email: "golstein@ciml.univ-mrs.fr" },
  { pi: "Richard Gomer", institution: "Texas A&M University", location: "College Station, USA", url: "https://www.bio.tamu.edu/lab-website-richard-gomer/", email: "rgomer@bio.tamu.edu" },
  { pi: "Eric Greer", institution: "Boston Children's Hospital / Harvard Medical School", location: "Boston, USA", url: "http://thegreerlab.com/", email: "eric.greer@childrens.harvard.edu" },
  { pi: "Jeffrey Hadwiger", institution: "Oklahoma State University", location: "Stillwater, USA", url: "", email: "jeff.hadwiger@okstate.edu" },
  { pi: "Christian Hammann", institution: "Jacobs University", location: "Bremen, Germany", url: "", email: "c.hammann@jacobs-university.de" },
  { pi: "Adrian Harwood", institution: "Cardiff University", location: "Cardiff, UK", url: "https://www.cardiff.ac.uk/people/view/58043-harwood-adrian", email: "harwoodaj@cardiff.ac.uk" },
  { pi: "Falk Hillmann", institution: "Hans-Knöll-Institut", location: "Jena, Germany", url: "https://www.leibniz-hki.de/en/institut-staff-details.html?member=12", email: "falk.hillmann@leibniz-hki.de" },
  { pi: "Robert Huber", institution: "Trent University", location: "Peterborough, Canada", url: "http://www.huberlab.ca/", email: "roberthuber@trentu.ca" },
  { pi: "Miho Iijima", institution: "Johns Hopkins University School of Medicine", location: "Baltimore, USA", url: "https://www.iijima-sesaki-lab.com/", email: "miijima@jhmi.edu" },
  { pi: "Robert Insall", institution: "Institute for Cancer Sciences, Glasgow University", location: "Glasgow, UK", url: "https://www.gla.ac.uk/researchinstitutes/cancersciences/research/units/bicr/rinsall/", email: "Robert.Insall@glasgow.ac.uk" },
  { pi: "Chris Janetopoulos", institution: "University of the Sciences", location: "Philadelphia, USA", url: "https://faculty.usciences.edu/faculty/janetopoulos-christopher" },
  { pi: "Tian Jin", institution: "National Institutes of Health", location: "Bethesda, USA", url: "https://www.niaid.nih.gov/research/tian-jin-phd", email: "tjin@niaid.nih.gov" },
  { pi: "Rob Kay", institution: "MRC Laboratory of Molecular Biology", location: "Cambridge, UK", url: "https://www2.mrc-lmb.cam.ac.uk/groups/rrk/research.php", emeritus: true, email: "rrk@mrc-lmb.ac.uk" },
  { pi: "Richard Kessin", institution: "Columbia University", location: "New York, USA", url: "https://sps.columbia.edu/faculty/richard-kessin", emeritus: true, email: "rhk2@columbia.edu" },
  { pi: "Alan Kimmel", institution: "National Institutes of Health", location: "Bethesda, USA", url: "https://www.niddk.nih.gov/about-niddk/staff-directory/biography/kimmel-alan", email: "ark1@helix.nih.gov" },
  { pi: "Jason King", institution: "University of Sheffield", location: "Sheffield, UK", url: "http://king.group.shef.ac.uk/", email: "jason.king@sheffield.ac.uk" },
  { pi: "David Knecht", institution: "University of Connecticut", location: "Storrs, USA", url: "https://mcb.uconn.edu/person/david-knecht/", email: "david.knecht@uconn.edu" },
  { pi: "Edward Korn", institution: "National Institutes of Health", location: "Bethesda, USA", url: "", emeritus: true },
  { pi: "Arjan Kortholt & Peter van Haastert", institution: "University of Groningen", location: "Groningen, Netherlands", url: "https://www.rug.nl/research/cell-biochemistry/staff", email: "a.kortholt@rug.nl, p.j.m.van.haastert@rug.nl" },
  { pi: "Scot Kuo", institution: "Johns Hopkins University", location: "Baltimore, USA", url: "http://www.jhu.edu/cmml/", email: "skuo@jhu.edu" },
  { pi: "Kei Inouye", institution: "Kyoto University", location: "Kyoto, Japan", url: "", email: "inoue@cosmos.bot.kyoto-u.ac.jp" },
  { pi: "Tera Levin", institution: "University of Pittsburgh", location: "Pittsburgh, USA", url: "https://www.teralevinlab.com/", email: "teralevin@pitt.edu" },
  { pi: "Markus Maniak", institution: "Kassel University", location: "Kassel, Germany", url: "", email: "maniak@uni-kassel.de" },
  { pi: "Dietmar Manstein", institution: "Hannover Medical School", location: "Hannover, Germany", url: "", email: "manstein.dietmar@mh-hannover.de" },
  { pi: "Stanley Mauldin", institution: "Holy Family University", location: "Philadelphia, USA", url: "" },
  { pi: "Annette Mueller-Taubenberger", institution: "Ludwig Maximilians University", location: "Munich, Germany", url: "https://www.en.bmc.med.uni-muenchen.de/research/research_areas/principal_investigators/mueller-taubenbergera/index.html", email: "amueller@bmc.med.lmu.de" },
  { pi: "Rupert Mutzel", institution: "Free University of Berlin", location: "Berlin, Germany", url: "http://www.biologie.fu-berlin.de/arbeitsgruppen/mikrobiologie/ag_mutzel/index.html", email: "rmutzel@zedat.fu-berlin.de" },
  { pi: "Vidya Nanjundiah", institution: "Indian Institute of Science", location: "Bangalore, India", url: "", emeritus: true, email: "vidya@alumni.iisc.ac.in" },
  { pi: "Suegene Noh", institution: "Colby College", location: "Waterville, USA", url: "", email: "snoh@colby.edu" },
  { pi: "Kari Naylor", institution: "University of Central Arkansas", location: "Conway, USA", url: "", email: "kknaylor@uca.edu" },
  { pi: "Justin Pachebat", institution: "Aberystwyth University", location: "Aberystwyth, UK", url: "https://www.aber.ac.uk/en/ibers/staff-profiles/listing/profile/jip/", email: "jip@aber.ac.uk" },
  { pi: "Carole Parent", institution: "University of Michigan", location: "Ann Arbor, USA", url: "https://www.lsi.umich.edu/science/our-labs/carole-parent-lab", email: "parentc@umich.edu" },
  { pi: "Young Shik Park", institution: "Inje University", location: "Kimhae, Korea", url: "http://home.inje.ac.kr/~biochemi/", email: "mbyspark@inje.ac.kr" },
  { pi: "Catherine Pears", institution: "Oxford University", location: "Oxford, UK", url: "", email: "catherine.pears@bioch.ox.ac.uk" },
  { pi: "Barbara Pergolizzi", institution: "University of Turin", location: "Turin, Italy", url: "", email: "barbara.pergolizzi@unito.it" },
  { pi: "Stefan Pukatzki", institution: "University of Alberta", location: "Edmonton, Canada", url: "", email: "spukatzki@ccny.cuny.edu" },
  { pi: "David Ratner", institution: "Amherst College", location: "Amherst, USA", url: "https://www.amherst.edu/people/facstaff/diratner", emeritus: true, email: "diratner@amherst.edu" },
  { pi: "Francisco Rivero", institution: "University of Hull", location: "Hull, UK", url: "", email: "F.Rivero-Crespo@hull.ac.uk" },
  { pi: "Douglas Robinson", institution: "Johns Hopkins University School of Medicine", location: "Baltimore, USA", url: "", email: "dnr@jhmi.edu" },
  { pi: "Matt Scaglione", institution: "Duke University School of Medicine", location: "Durham, USA", url: "", email: "matt.scaglione@duke.edu" },
  { pi: "Pauline Schaap", institution: "University of Dundee", location: "Dundee, Scotland", url: "", email: "p.schaap@dundee.ac.uk" },
  { pi: "Jeff Segall", institution: "Albert Einstein College of Medicine", location: "Bronx, USA", url: "", email: "jeffrey.segall@einsteinmed.edu" },
  { pi: "Gad Shaulsky", institution: "Baylor College of Medicine", location: "Houston, USA", url: "", email: "gadi@bcm.edu" },
  { pi: "Longfei Shu", institution: "Sun Yat-sen University", location: "Guangzhou, China", url: "", email: "shulf@mail.sysu.edu.cn" },
  { pi: "Charles Singleton", institution: "Vanderbilt University", location: "Nashville, USA", url: "", emeritus: true, email: "Charles.K.Singleton@vanderbilt.edu" },
  { pi: "Fredrik Söderbom", institution: "University of Uppsala", location: "Uppsala, Sweden", url: "", email: "fredrik.soderbom@icm.uu.se" },
  { pi: "Thierry Soldati", institution: "University of Geneva", location: "Geneva, Switzerland", url: "", email: "Thierry.Soldati@unige.ch" },
  { pi: "David Soll", institution: "University of Iowa", location: "Iowa City, USA", url: "", email: "david-soll@uiowa.edu" },
  { pi: "Glaucia Souza", institution: "University of São Paulo", location: "São Paulo, Brazil", url: "", email: "glmsouza@iq.usp.br" },
  { pi: "Pierre Stallforth", institution: "Hans Knöll Institut", location: "Jena, Germany", url: "", email: "pierre.stallforth@leibniz-hki.de" },
  { pi: "Paul Steimle", institution: "University of North Carolina at Greensboro", location: "Greensboro, USA", url: "", email: "p_steiml@uncg.edu" },
  { pi: "Joan Strassmann & David Queller", institution: "Washington University in St. Louis", location: "St. Louis, USA", url: "", email: "strassmann@wustl.edu, queller@wustl.edu" },
  { pi: "Christopher Thompson", institution: "University College London", location: "London, UK", url: "https://thethompsonlab.wordpress.com/", email: "christopher.thompson@ucl.ac.uk" },
  { pi: "Elinor Thompson", institution: "University of Greenwich", location: "Greenwich, UK", url: "", email: "e.thompson@gre.ac.uk" },
  { pi: "Igor Weber", institution: "Ruđer Bošković Institute", location: "Zagreb, Croatia", url: "", email: "iweber@irb.hr" },
  { pi: "Gerald Weeks", institution: "University of British Columbia", location: "Vancouver, Canada", url: "", emeritus: true, email: "gerwee@mail.ubc.ca" },
  { pi: "Cornelius Weijer", institution: "University of Dundee", location: "Dundee, Scotland", url: "", email: "c.j.weijer@dundee.ac.uk" },
  { pi: "Christopher West", institution: "University of Georgia", location: "Athens, USA", url: "", email: "westcm@uga.edu" },
  { pi: "Claire Wilhelm", institution: "Université Paris", location: "Paris, France", url: "", email: "claire.wilhelm@cnrs.fr" },
  { pi: "Jeffrey Williams", institution: "University of Dundee", location: "Dundee, Scotland", url: "" },
  { pi: "Robin Williams", institution: "Royal Holloway University of London", location: "London, UK", url: "", email: "robin.williams@rhul.ac.uk" },
  { pi: "Thomas Winckler", institution: "Jena University", location: "Jena, Germany", url: "", email: "t.winckler@uni-jena.de" },
];
