window.dictyLabs = [
  { pi: "Stephen Alexander", institution: "University of Missouri", location: "Columbia, USA", url: "", email: "dWRlLmlydW9zc2ltQHRzcmVkbmF4ZWxh" },
  { pi: "Caroline Barisch", institution: "University of Osnabrück", location: "Osnabrück, Germany", url: "", email: "ZWQuc291QGhjc2lyYUIuZW5pbG9yYUM=" },
  { pi: "Ramamurthy Baskar", institution: "IIT Madras", location: "Chennai, India", url: "", email: "bmkuY2EubXRpaUByYWtzYWJy" },
  { pi: "Carsten Beta", institution: "University of Potsdam", location: "Potsdam, Germany", url: "https://www.uni-potsdam.de/en/biophysik/reseach/overview.html", email: "ZWQubWFkc3RvcC1pbnVAYXRlYi5uZXRzcmFj" },
  { pi: "Brenda Blacklock", institution: "Purdue School of Science", location: "Indianapolis, USA", url: "https://science.iupui.edu/people-directory/people/blacklock-brenda.html", email: "dWRlLml1cHVpQG9sa2NhbGJi" },
  { pi: "Gareth Bloomfield", institution: "MRC Laboratory of Molecular Biology", location: "Cambridge, UK", url: "https://gareths.space/" },
  { pi: "Salvo Bozzaro", institution: "University of Turin", location: "Turin, Italy", url: "https://www.dscb.unito.it/do/gruppi.pl/Show?_id=rq0i", emeritus: true, email: "dGkub3RpbnVAb3JhenpvYi5lcm90YXZsYXM=" },
  { pi: "Derrick Brazill", institution: "Hunter College", location: "New York, USA", url: "", email: "dWRlLnludWMucmV0bnVoLnJ0Y2VuZWdAbGxpemFyYg==" },
  { pi: "Huaqing Cai", institution: "Institute of Biophysics, Chinese Academy of Sciences", location: "Beijing, China", url: "", email: "bmMuY2EucGJpQGlhY2duaXFhdWg=" },
  { pi: "Pascale Charest", institution: "University of Arizona", location: "Tucson, USA", url: "https://www.thecharestlab.org/", email: "dWRlLmFub3ppcmFAdHNlcmFoY3A=" },
  { pi: "Steve Charette", institution: "Université Laval", location: "Québec, Canada", url: "http://www.amibe.org/", email: "YWMubGF2YWx1Lm1jYkBldHRlcmFoQy5ldmV0Uw==" },
  { pi: "Jonathan Chubb", institution: "UCL London", location: "London, UK", url: "https://www.ucl.ac.uk/lmcb/users/jonathan-chubb", email: "a3UuY2EubGN1QGJidWhjLmo=" },
  { pi: "Chang Chung", institution: "Vanderbilt University", location: "Nashville, USA", url: "" },
  { pi: "Pierre Cosson", institution: "University of Geneva", location: "Geneva, Switzerland", url: "", email: "aGMuZWdpbnVAbm9zc29jLmVycmVpcA==" },
  { pi: "Aline da Silva", institution: "University of São Paulo", location: "São Paulo, Brazil", url: "" },
  { pi: "Cynthia Damer", institution: "Central Michigan University", location: "Mount Pleasant, USA", url: "", email: "dWRlLmhjaW1jQGtjMXJlbWFk" },
  { pi: "Arturo DeLozanne", institution: "University of Texas at Austin", location: "Austin, USA", url: "http://www.zo.utexas.edu/faculty/delozanne/adlab.html", email: "dWRlLnNheGV0dUBlbm5hem9sZWQuYQ==" },
  { pi: "Peter Devreotes", institution: "Johns Hopkins University", location: "Baltimore, USA", url: "http://devreotes.johnshopkins.edu/", email: "dWRlLmltaGpAZG5w" },
  { pi: "Robert Dottin", institution: "Hunter College", location: "New York, USA", url: "", email: "dWRlLnludWMucmV0bnVoLnJ0Y2VuZWdAbml0dG9k" },
  { pi: "Danton O'Day", institution: "University of Toronto at Mississauga", location: "Mississauga, Canada", url: "", email: "YWMub3Rub3JvdHVAeWFkby5ub3RuYWQ=" },
  { pi: "Ludwig Eichinger", institution: "University of Cologne", location: "Cologne, Germany", url: "", email: "ZWQubmxlb2staW51QHJlZ25paGNpZS5naXdkdWw=" },
  { pi: "Ricardo Escalante", institution: "Instituto de Investigaciones Biomedicas", location: "Madrid, Spain", url: "http://www2.iib.uam.es/rescalante_lab/Sitio_web/Escalante_Lab.html", email: "c2UubWF1LmJpaUBldG5hbGFjc2Vy" },
  { pi: "Richard Firtel", institution: "UC San Diego", location: "San Diego, USA", url: "http://biology.ucsd.edu/research/faculty/rafirtel", email: "dWRlLmRzY3VAbGV0cmlmYXI=" },
  { pi: "Paul Fisher", institution: "La Trobe University", location: "Victoria, Australia", url: "https://scholars.latrobe.edu.au/display/prfisher", email: "dWEudWRlLmVib3J0YWxAcmVoc2lGLlA=" },
  { pi: "Carl Franck", institution: "Cornell University", location: "Ithaca, USA", url: "https://franckgroup.lassp.cornell.edu/", email: "dWRlLmxsZW5yb2NAMWZwYw==" },
  { pi: "Günther Gerisch", institution: "Max Planck Institute of Biochemistry", location: "Martinsried, Germany", url: "http://www.biochem.mpg.de/gerisch/", emeritus: true },
  { pi: "Pierre Golstein", institution: "Centre d'Immunologie de Marseille-Luminy", location: "Marseille, France", url: "", email: "cmYuc3JtLXZpbnUubG1pY0BuaWV0c2xvZw==" },
  { pi: "Richard Gomer", institution: "Texas A&M University", location: "College Station, USA", url: "https://www.bio.tamu.edu/lab-website-richard-gomer/", email: "dWRlLnVtYXQub2liQHJlbW9ncg==" },
  { pi: "Eric Greer", institution: "Boston Children's Hospital / Harvard Medical School", location: "Boston, USA", url: "http://thegreerlab.com/", email: "dWRlLmRyYXZyYWguc25lcmRsaWhjQHJlZXJnLmNpcmU=" },
  { pi: "Jeffrey Hadwiger", institution: "Oklahoma State University", location: "Stillwater, USA", url: "", email: "dWRlLmV0YXRza29AcmVnaXdkYWguZmZlag==" },
  { pi: "Christian Hammann", institution: "Jacobs University", location: "Bremen, Germany", url: "", email: "ZWQueXRpc3JldmludS1zYm9jYWpAbm5hbW1haC5j" },
  { pi: "Adrian Harwood", institution: "Cardiff University", location: "Cardiff, UK", url: "https://www.cardiff.ac.uk/people/view/58043-harwood-adrian", email: "a3UuY2EuZmZpZHJhY0BqYWRvb3dyYWg=" },
  { pi: "Falk Hillmann", institution: "Hans-Knöll-Institut", location: "Jena, Germany", url: "https://www.leibniz-hki.de/en/institut-staff-details.html?member=12", email: "ZWQuaWtoLXppbmJpZWxAbm5hbWxsaWgua2xhZg==" },
  { pi: "Robert Huber", institution: "Trent University", location: "Peterborough, Canada", url: "http://www.huberlab.ca/", email: "YWMudXRuZXJ0QHJlYnVodHJlYm9y" },
  { pi: "Miho Iijima", institution: "Johns Hopkins University School of Medicine", location: "Baltimore, USA", url: "https://www.iijima-sesaki-lab.com/", email: "dWRlLmltaGpAYW1pamlpbQ==" },
  { pi: "Robert Insall", institution: "Institute for Cancer Sciences, Glasgow University", location: "Glasgow, UK", url: "https://www.gla.ac.uk/researchinstitutes/cancersciences/research/units/bicr/rinsall/", email: "a3UuY2Eud29nc2FsZ0BsbGFzbkkudHJlYm9S" },
  { pi: "Chris Janetopoulos", institution: "University of the Sciences", location: "Philadelphia, USA", url: "https://faculty.usciences.edu/faculty/janetopoulos-christopher" },
  { pi: "Tian Jin", institution: "National Institutes of Health", location: "Bethesda, USA", url: "https://www.niaid.nih.gov/research/tian-jin-phd", email: "dm9nLmhpbi5kaWFpbkBuaWp0" },
  { pi: "Rob Kay", institution: "MRC Laboratory of Molecular Biology", location: "Cambridge, UK", url: "https://www2.mrc-lmb.cam.ac.uk/groups/rrk/research.php", emeritus: true, email: "a3UuY2EuYm1sLWNybUBrcnI=" },
  { pi: "Richard Kessin", institution: "Columbia University", location: "New York, USA", url: "https://sps.columbia.edu/faculty/richard-kessin", emeritus: true, email: "dWRlLmFpYm11bG9jQDJraHI=" },
  { pi: "Alan Kimmel", institution: "National Institutes of Health", location: "Bethesda, USA", url: "https://www.niddk.nih.gov/about-niddk/staff-directory/biography/kimmel-alan", email: "dm9nLmhpbi54aWxlaEAxa3Jh" },
  { pi: "Jason King", institution: "University of Sheffield", location: "Sheffield, UK", url: "http://king.group.shef.ac.uk/", email: "a3UuY2EuZGxlaWZmZWhzQGduaWsubm9zYWo=" },
  { pi: "David Knecht", institution: "University of Connecticut", location: "Storrs, USA", url: "https://mcb.uconn.edu/person/david-knecht/", email: "dWRlLm5ub2N1QHRoY2Vuay5kaXZhZA==" },
  { pi: "Edward Korn", institution: "National Institutes of Health", location: "Bethesda, USA", url: "", emeritus: true },
  { pi: "Arjan Kortholt & Peter van Haastert", institution: "University of Groningen", location: "Groningen, Netherlands", url: "https://www.rug.nl/research/cell-biochemistry/staff", email: "bG4uZ3VyQHRyZXRzYWFoLm5hdi5tLmoucCAsbG4uZ3VyQHRsb2h0cm9rLmE=" },
  { pi: "Scot Kuo", institution: "Johns Hopkins University", location: "Baltimore, USA", url: "http://www.jhu.edu/cmml/", email: "dWRlLnVoakBvdWtz" },
  { pi: "Kei Inouye", institution: "Kyoto University", location: "Kyoto, Japan", url: "", email: "cGouY2EudS1vdG95ay50b2Iuc29tc29jQGV1b25p" },
  { pi: "Tera Levin", institution: "University of Pittsburgh", location: "Pittsburgh, USA", url: "https://www.teralevinlab.com/", email: "dWRlLnR0aXBAbml2ZWxhcmV0" },
  { pi: "Markus Maniak", institution: "Kassel University", location: "Kassel, Germany", url: "", email: "ZWQubGVzc2FrLWludUBrYWluYW0=" },
  { pi: "Dietmar Manstein", institution: "Hannover Medical School", location: "Hannover, Germany", url: "", email: "ZWQucmV2b25uYWgtaG1AcmFtdGVpZC5uaWV0c25hbQ==" },
  { pi: "Stanley Mauldin", institution: "Holy Family University", location: "Philadelphia, USA", url: "" },
  { pi: "Annette Mueller-Taubenberger", institution: "Ludwig Maximilians University", location: "Munich, Germany", url: "https://www.en.bmc.med.uni-muenchen.de/research/research_areas/principal_investigators/mueller-taubenbergera/index.html", email: "ZWQudW1sLmRlbS5jbWJAcmVsbGV1bWE=" },
  { pi: "Rupert Mutzel", institution: "Free University of Berlin", location: "Berlin, Germany", url: "http://www.biologie.fu-berlin.de/arbeitsgruppen/mikrobiologie/ag_mutzel/index.html", email: "ZWQubmlscmViLXVmLnRhZGV6QGxlenR1bXI=" },
  { pi: "Vidya Nanjundiah", institution: "Indian Institute of Science", location: "Bangalore, India", url: "", emeritus: true, email: "bmkuY2EuY3NpaS5pbm11bGFAYXlkaXY=" },
  { pi: "Suegene Noh", institution: "Colby College", location: "Waterville, USA", url: "", email: "dWRlLnlibG9jQGhvbnM=" },
  { pi: "Kari Naylor", institution: "University of Central Arkansas", location: "Conway, USA", url: "", email: "dWRlLmFjdUByb2x5YW5raw==" },
  { pi: "Justin Pachebat", institution: "Aberystwyth University", location: "Aberystwyth, UK", url: "https://www.aber.ac.uk/en/ibers/staff-profiles/listing/profile/jip/", email: "a3UuY2EucmViYUBwaWo=" },
  { pi: "Carole Parent", institution: "University of Michigan", location: "Ann Arbor, USA", url: "https://www.lsi.umich.edu/science/our-labs/carole-parent-lab", email: "dWRlLmhjaW11QGN0bmVyYXA=" },
  { pi: "Young Shik Park", institution: "Inje University", location: "Kimhae, Korea", url: "http://home.inje.ac.kr/~biochemi/", email: "cmsuY2EuZWpuaUBrcmFwc3libQ==" },
  { pi: "Catherine Pears", institution: "Oxford University", location: "Oxford, UK", url: "", email: "a3UuY2EueG8uaGNvaWJAc3JhZXAuZW5pcmVodGFj" },
  { pi: "Barbara Pergolizzi", institution: "University of Turin", location: "Turin, Italy", url: "", email: "dGkub3RpbnVAaXp6aWxvZ3JlcC5hcmFicmFi" },
  { pi: "Stefan Pukatzki", institution: "City College of New York (CUNY)", location: "New York, USA", url: "", email: "dWRlLnludWMueW5jY0Bpa3p0YWt1cHM=" },
  { pi: "David Ratner", institution: "Amherst College", location: "Amherst, USA", url: "https://www.amherst.edu/people/facstaff/diratner", emeritus: true, email: "dWRlLnRzcmVobWFAcmVudGFyaWQ=" },
  { pi: "Francisco Rivero", institution: "University of Hull", location: "Hull, UK", url: "", email: "a3UuY2EubGx1aEBvcHNlckMtb3JldmlSLkY=" },
  { pi: "Douglas Robinson", institution: "Johns Hopkins University School of Medicine", location: "Baltimore, USA", url: "", email: "dWRlLmltaGpAcm5k" },
  { pi: "Matt Scaglione", institution: "Duke University School of Medicine", location: "Durham, USA", url: "", email: "dWRlLmVrdWRAZW5vaWxnYWNzLnR0YW0=" },
  { pi: "Pauline Schaap", institution: "University of Dundee", location: "Dundee, Scotland", url: "", email: "a3UuY2EuZWVkbnVkQHBhYWhjcy5w" },
  { pi: "Jeff Segall", institution: "Albert Einstein College of Medicine", location: "Bronx, USA", url: "", email: "dWRlLmRlbW5pZXRzbmllQGxsYWdlcy55ZXJmZmVq" },
  { pi: "Gad Shaulsky", institution: "Baylor College of Medicine", location: "Houston, USA", url: "", email: "dWRlLm1jYkBpZGFn" },
  { pi: "Longfei Shu", institution: "Sun Yat-sen University", location: "Guangzhou, China", url: "", email: "bmMudWRlLnVzeXMubGlhbUBmbHVocw==" },
  { pi: "Charles Singleton", institution: "Vanderbilt University", location: "Nashville, USA", url: "", emeritus: true, email: "dWRlLnRsaWJyZWRuYXZAbm90ZWxnbmlTLksuc2VscmFoQw==" },
  { pi: "Fredrik Söderbom", institution: "University of Uppsala", location: "Uppsala, Sweden", url: "", email: "ZXMudXUubWNpQG1vYnJlZG9zLmtpcmRlcmY=" },
  { pi: "Thierry Soldati", institution: "University of Geneva", location: "Geneva, Switzerland", url: "", email: "aGMuZWdpbnVAaXRhZGxvUy55cnJlaWhU" },
  { pi: "David Soll", institution: "University of Iowa", location: "Iowa City, USA", url: "", email: "dWRlLmF3b2l1QGxsb3MtZGl2YWQ=" },
  { pi: "Glaucia Souza", institution: "University of São Paulo", location: "São Paulo, Brazil", url: "", email: "cmIucHN1LnFpQGF6dW9zbWxn" },
  { pi: "Pierre Stallforth", institution: "Hans Knöll Institut", location: "Jena, Germany", url: "", email: "ZWQuaWtoLXppbmJpZWxAaHRyb2ZsbGF0cy5lcnJlaXA=" },
  { pi: "Paul Steimle", institution: "University of North Carolina at Greensboro", location: "Greensboro, USA", url: "", email: "dWRlLmdjbnVAbG1pZXRzX3A=" },
  { pi: "Joan Strassmann & David Queller", institution: "Washington University in St. Louis", location: "St. Louis, USA", url: "", email: "dWRlLmx0c3V3QHJlbGxldXEgLHVkZS5sdHN1d0BubmFtc3NhcnRz" },
  { pi: "Christopher Thompson", institution: "University College London", location: "London, UK", url: "https://thethompsonlab.wordpress.com/", email: "a3UuY2EubGN1QG5vc3Btb2h0LnJlaHBvdHNpcmhj" },
  { pi: "Elinor Thompson", institution: "University of Greenwich", location: "Greenwich, UK", url: "", email: "a3UuY2EuZXJnQG5vc3Btb2h0LmU=" },
  { pi: "Igor Weber", institution: "Ruđer Bošković Institute", location: "Zagreb, Croatia", url: "", email: "cmguYnJpQHJlYmV3aQ==" },
  { pi: "Gerald Weeks", institution: "University of British Columbia", location: "Vancouver, Canada", url: "", emeritus: true, email: "YWMuY2J1LmxpYW1AZWV3cmVn" },
  { pi: "Cornelius Weijer", institution: "University of Dundee", location: "Dundee, Scotland", url: "", email: "a3UuY2EuZWVkbnVkQHJlamlldy5qLmM=" },
  { pi: "Christopher West", institution: "University of Georgia", location: "Athens, USA", url: "", email: "dWRlLmFndUBtY3RzZXc=" },
  { pi: "Claire Wilhelm", institution: "Université Paris", location: "Paris, France", url: "", email: "cmYuc3JuY0BtbGVobGl3LmVyaWFsYw==" },
  { pi: "Jeffrey Williams", institution: "University of Dundee", location: "Dundee, Scotland", url: "" },
  { pi: "Robin Williams", institution: "Royal Holloway University of London", location: "London, UK", url: "", email: "a3UuY2EubHVockBzbWFpbGxpdy5uaWJvcg==" },
  { pi: "Thomas Winckler", institution: "Jena University", location: "Jena, Germany", url: "", email: "ZWQuYW5lai1pbnVAcmVsa2NuaXcudA==" },
];
