#!/usr/bin/env python3
"""Generate the synthetic fixture bundles. Stdlib only, fully seeded.

Two invented organisms with deliberately different identifier styles, fraction
designs and compartment sets, so nothing downstream can lean on one organism's
conventions. Every value is made up; the bundles are flagged synthetic.

    python3 spatial/tests/fixtures/make_fixtures.py
"""
import math
import pathlib
import random
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / "py"))
from spatialprot import bundle as B  # noqa: E402

BUILT = "2026-10-09"  # fixed so regeneration is byte-stable


def dataset(ds_id, title, organism, namespaces, entities, mapping_method):
    return {
        "id": ds_id,
        "title": title,
        "description": "Synthetic data generated for software tests. Not a biological result.",
        "organism": organism,
        "citation": {"text": "Synthetic fixture, spatialprot test suite. No publication.",
                     "peer_reviewed": False},
        "license": {"id": "CC0-1.0", "name": "Creative Commons Zero 1.0",
                    "url": "https://creativecommons.org/publicdomain/zero/1.0/",
                    "redistribution": "permitted"},
        "attribution": "Generated by spatial/tests/fixtures/make_fixtures.py.",
        "provenance": {"builder": "make_fixtures.py", "built": BUILT,
                       "sources": [{"name": "make_fixtures.py",
                                    "description": "Seeded pseudo-random generator; no experimental input."}],
                       "steps": ["Draw a compartment per protein group.",
                                 "Draw a profile around that compartment's template.",
                                 "Derive the example layers from the drawn values."]},
        "id_namespaces": namespaces,
        "mapping": B.mapping_stats(entities, mapping_method, source="synthetic"),
        "distribution": {"status": "public", "reason": "Synthetic, CC0."},
        "synthetic": True,
    }


def template(n_fractions, peak, width):
    return [math.exp(-((i - peak) ** 2) / (2 * width ** 2)) + 0.02 for i in range(n_fractions)]


def draw_profile(rng, templates, noise, mix=None):
    base = templates[0] if mix is None else [a * (1 - mix) + b * mix for a, b in zip(*templates)]
    vec = [max(0.0, v * rng.uniform(0.8, 1.2) + rng.gauss(0, noise)) for v in base]
    total = sum(vec) or 1.0
    return [round(v / total, 5) for v in vec]


def corr(a, b):
    ma, mb = sum(a) / len(a), sum(b) / len(b)
    num = sum((x - ma) * (y - mb) for x, y in zip(a, b))
    den = math.sqrt(sum((x - ma) ** 2 for x in a) * sum((y - mb) ** 2 for y in b))
    return num / den if den else 0.0


def simulate(rng, comps, n_fractions, n_entities, repeats=1):
    """Return per-entity truth, profile and a classifier-like (class, score)."""
    n_unique = n_fractions // repeats
    tmpl = {c: template(n_unique, 0.5 + i * (n_unique - 1) / max(1, len(comps) - 1) * 0.95, 0.9) * repeats
            for i, c in enumerate(comps)}
    rows = []
    for k in range(n_entities):
        truth = comps[k % len(comps)] if k < 3 * len(comps) else rng.choice(comps)
        mixed = k >= 3 * len(comps) and rng.random() < 0.3
        other = rng.choice([c for c in comps if c != truth])
        prof = draw_profile(rng, (tmpl[truth], tmpl[other]), 0.03,
                            mix=rng.uniform(0.3, 0.5) if mixed else 0.0)
        scored = sorted(((corr(prof, tmpl[c]), c) for c in comps), reverse=True)
        best, runner = scored[0], scored[1]
        score = round(max(0.05, min(0.99, 0.2 + (best[0] - runner[0]) * 0.4 + rng.gauss(0, 0.03))), 6)
        rows.append({"truth": truth, "profile": prof, "klass": best[1], "score": score})
    return rows


def median(xs):
    s = sorted(xs)
    n = len(s)
    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2


def classifier_layer(layer_id, label, ids, rows, score_block):
    thr = median([r["score"] for r in rows])
    score_block = dict(score_block)
    score_block["threshold"] = {"value": thr, "rule": "score >= value", "basis": "stated_by_source",
                                "description": "Median of all scores."}
    return {
        "id": layer_id, "label": label, "evidence_type": "computational_assignment",
        "source": "author",
        "method": {"name": "synthetic classifier",
                   "description": "Stand-in for a supervised classifier trained on marker profiles."},
        "score": score_block,
        "assignments": [{"entity": i, "compartment": r["klass"],
                         "status": "assigned" if r["score"] >= thr else "below_threshold",
                         "score": r["score"]} for i, r in zip(ids, rows)],
    }


def alpha():
    """Exemplum primum: accession-list entity ids, one condition, author embedding."""
    rng = random.Random(1101)
    comps = ["cyt", "mem", "nuc", "mit"]
    labels = {"cyt": "Cytosol", "mem": "Membrane", "nuc": "Nucleus", "mit": "Mitochondrion"}
    n, nf = 80, 8
    rows = simulate(rng, comps, nf, n)
    entities = []
    for k in range(n):
        members = [{"id": f"EP_P{k + 1:04d}", "gene": f"EPG{k + 1:04d}"}]
        if k in (5, 17, 33, 61):            # groups spanning two genes
            members.append({"id": f"EP_P{900 + k:04d}", "gene": f"EPG{900 + k:04d}"})
        if k in (12, 40):                   # two isoforms of one gene
            members.append({"id": f"EP_P{k + 1:04d}b", "gene": f"EPG{k + 1:04d}"})
        if k in (7, 29, 52):                # no gene model for this accession
            members = [{"id": f"EP_X{k + 1:04d}", "gene": None}]
        if k == 70:                         # partly mapped group
            members.append({"id": "EP_X9070", "gene": None})
        ent = {"id": ";".join(m["id"] for m in members), "members": members}
        if k in (7, 29, 52):
            ent["mapping_note"] = "Accession absent from the gene mapping source."
        entities.append(ent)
    entities[10]["members"][0]["gene"] = entities[9]["members"][0]["gene"]  # one gene, two groups
    ids = [e["id"] for e in entities]

    markers = {"id": "markers", "label": "Reference markers", "short_label": "Marker", "evidence_type": "curated_annotation",
               "source": "author",
               "method": {"name": "curated marker set",
                          "description": "Proteins with an accepted location, chosen by the authors."},
               "attribute_labels": {"used_for_training": "Used to train the classifier"},
               "assignments": [{"entity": ids[k], "compartment": rows[k]["truth"], "status": "assigned",
                                "attributes": {"used_for_training": k % 3 != 2}}
                               for k in range(3 * len(comps))]}
    clf = classifier_layer("classifier", "Classifier assignment", ids, rows,
                           {"name": "classifier.score", "interpretation": "unspecified",
                            "description": "Score reported by the classifier. Its scale is not defined by the source."})
    clf["trained_on"] = ["markers"]
    clf["status_labels"] = {"below_threshold": "unknown"}
    seq = {"id": "targeting", "label": "Targeting signal prediction", "evidence_type": "sequence_prediction",
           "source": "external", "compartment_scope": ["mit"],
           "method": {"name": "synthetic targeting predictor",
                      "description": "Stand-in for a sequence-based presequence predictor."},
           "score": {"name": "presequence_probability", "interpretation": "probability",
                     "interpretation_basis": "Defined as a posterior probability by the (synthetic) predictor.",
                     "threshold": {"value": 0.5, "rule": "score >= value", "basis": "stated_by_source"}},
           "assignments": []}
    for k in range(0, n, 2):
        p = round(rng.uniform(0.55, 0.98) if rows[k]["truth"] == "mit" else rng.uniform(0.01, 0.6), 4)
        seq["assignments"].append({"entity": ids[k], "compartment": "mit",
                                   "status": "assigned" if p >= 0.5 else "below_threshold", "score": p})

    wx = [rng.uniform(-1, 1) for _ in range(nf)]
    wy = [rng.uniform(-1, 1) for _ in range(nf)]
    coords = {i: [round(sum(a * b for a, b in zip(r["profile"], wx)) * 40 + rng.gauss(0, 0.4), 4),
                  round(sum(a * b for a, b in zip(r["profile"], wy)) * 40 + rng.gauss(0, 0.4), 4)]
              for i, r in zip(ids, rows)}
    profiles = {i: r["profile"] for i, r in zip(ids, rows)}
    profiles[ids[3]] = profiles[ids[3]][:-1] + [None]   # one missing measurement
    ds = dataset("synthetic-alpha", "Synthetic spatial map, Exemplum primum",
                 {"name": "Exemplum primum", "taxon_id": None, "strain": "EP1", "condition": "synthetic"},
                 {"entity": "accession list", "member": "ep_protein", "gene": "ep_gene"},
                 entities, "Synthetic one-to-one table with planted exceptions.")
    return B.new_bundle(
        ds,
        [{"id": c, "label": labels[c]} for c in comps],
        entities, [markers, clf, seq],
        fractions=[{"id": f"F{i + 1}", "label": f"Fraction {i + 1}"} for i in range(nf)],
        profiles={"evidence_type": "measured_profile", "source": "author",
                  "unit": "fraction of summed intensity", "processing": "Synthetic; rows sum to 1.",
                  "values": profiles},
        embeddings=[{"id": "author-map", "label": "Author-supplied map (synthetic)",
                     "method": {"name": "synthetic projection",
                                "description": "Stand-in for coordinates supplied with a publication."},
                     "source": "author", "derived_from": "profiles",
                     "axes": ["Dimension 1", "Dimension 2"], "coordinates": coords}])


def beta():
    """Fictus alter: opaque group ids, two lysis conditions, no embedding supplied."""
    rng = random.Random(2202)
    comps = ["GO:9000001", "GO:9000002", "GO:9000003", "GO:9000004", "GO:9000005", "GO:9000006"]
    labels = ["Cortex", "Vacuole", "Plastid", "Nucleolus", "Cell wall", "Lipid droplet"]
    n, per = 120, 5
    rows = simulate(rng, comps, per * 2, n, repeats=2)
    entities = []
    for k in range(n):
        members = [{"id": f"fa|prot-{k + 1:04d}.a", "gene": f"locus:FA_{k + 1:04d}",
                    "description": f"synthetic protein {k + 1}"}]
        if k % 20 == 3:
            members += [{"id": f"fa|prot-{k + 501:04d}.a", "gene": f"locus:FA_{k + 501:04d}"},
                        {"id": f"fa|prot-{k + 701:04d}.a", "gene": f"locus:FA_{k + 701:04d}"}]
        if k % 40 == 9:
            members = [{"id": f"fa|orf-{k + 1:04d}", "gene": None}]
        entities.append({"id": f"grp-{k + 1:04d}", "label": f"FaP{k + 1}", "members": members})
    ids = [e["id"] for e in entities]
    ref = {"id": "reference-set", "label": "Curated reference set", "evidence_type": "curated_annotation",
           "source": "external",
           "method": {"name": "literature curation",
                      "description": "Locations taken from a (synthetic) curated knowledgebase."},
           "assignments": [{"entity": ids[k], "compartment": rows[k]["truth"], "status": "assigned"}
                           for k in range(3 * len(comps))]}
    ref["assignments"][0]["others"] = [comps[3]]           # annotated to two places
    ref["assignments"][7]["others"] = [comps[0], comps[5]]
    clf = classifier_layer("model", "Model assignment", ids, rows,
                           {"name": "posterior", "interpretation": "probability",
                            "interpretation_basis": "The (synthetic) method defines this value as a posterior probability."})
    fractions = [{"id": f"{cond}-{i + 1}", "label": f"{cond} {i + 1}", "condition": cond}
                 for cond in ("mild", "harsh") for i in range(per)]
    ds = dataset("synthetic-beta", "Synthetic spatial map, Fictus alter",
                 {"name": "Fictus alter", "taxon_id": None, "condition": "synthetic"},
                 {"entity": "group id", "member": "fa_protein", "gene": "fa_locus"},
                 entities, "Synthetic table with planted multi-gene and unmapped groups.")
    return B.new_bundle(
        ds, [{"id": c, "label": l, "ontology_id": c} for c, l in zip(comps, labels)],
        entities, [ref, clf], fractions=fractions,
        profiles={"evidence_type": "measured_profile", "source": "author",
                  "unit": "fraction of summed intensity", "processing": "Synthetic; rows sum to 1.",
                  "values": {i: r["profile"] for i, r in zip(ids, rows)}})


def assignments_only(bundle):
    """The same experiment as published without profiles or coordinates."""
    out = {k: v for k, v in bundle.items() if k not in ("fractions", "profiles", "embeddings")}
    out["dataset"] = dict(bundle["dataset"], id=bundle["dataset"]["id"] + "-assignments-only",
                          title=bundle["dataset"]["title"] + " (assignments only)",
                          notices=["Profiles and map coordinates have not been supplied for this example."])
    return out


def build_all():
    a = alpha()
    return {"alpha.bundle.json": a, "beta.bundle.json": beta(),
            "alpha.assignments-only.bundle.json": assignments_only(a)}


def expected(bundles):
    """Reference answers from the Python implementation. The JavaScript tests
    must reproduce them, so the two implementations cannot drift apart."""
    from spatialprot import summary as S
    out = {}
    for name, b in bundles.items():
        ids = [l["id"] for l in b["layers"]]
        shared = sorted(g for g, v in B.gene_index(b).items() if len(v) > 1)
        out[name] = {
            "layer_counts": {i: S.layer_counts(b, i)["compartments"] for i in ids},
            "concordance": {f"{x}|{y}": {k: v for k, v in S.concordance(b, x, y).items() if k.startswith("n_") or k == "table"}
                            for x in ids for y in ids if x != y},
            "detected_genes": S.detected_genes(b),
            "detected_single_gene_genes": S.detected_genes(b, single_gene_only=True),
            "study_all": S.study_genes(b, [e["id"] for e in b["entities"]]),
            "scopes": {f"{x}|{y}": (sorted(S.shared_scope(b, x, y)) if S.shared_scope(b, x, y) is not None else None)
                       for x in ids for y in ids if x != y},
            "gene_groups": {g: B.gene_index(b)[g] for g in shared},
            "mapping_status": {e["id"]: B.entity_mapping_status(e) for e in b["entities"]},
        }
    return out


if __name__ == "__main__":
    import json
    built = build_all()
    for name, bundle in built.items():
        B.dump(bundle, HERE / name)
        print("wrote", name)
    (HERE / "expected.json").write_text(json.dumps(expected(built), sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8")
    print("wrote expected.json")
