#!/usr/bin/env python3
"""Generate the front-page news feed (assets/news.json) from two sources:

  1. assets/news_manual.json   — hand-curated entries (welcome post, etc.)
  2. `News:` trailers in git commit messages — one per feature, written once
     at commit time so the feed stays current as you ship.

Run it whenever you want the feed refreshed (and commit the result):

    python3 scripts/build_news.py

Commit-trailer format (anywhere in the commit message, one per line):

    News: [tag] Title of the update | One or two sentence body. | /optional/link

  - [tag] is optional; one of new|update|data|community (default: update).
  - Fields are split on " | ": title, then body, then an optional link.
  - The date is the commit's author date; the short hash dedupes re-runs.

Example commit message:

    Add a paralog finder to the Orthologs tab

    News: [new] Find paralogs and gene families | The Orthologs tab now
    lists a gene's closest paralogs across the AX4 genome. | /gene/rasG

Newest first. Output is capped (MAX_ITEMS) so the feed stays tidy; the full
history still lives in git. Falls back to the manual entries alone if git is
unavailable.
"""
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANUAL = os.path.join(ROOT, "assets", "news_manual.json")
OUT = os.path.join(ROOT, "assets", "news.json")
MAX_ITEMS = 12
VALID_TAGS = {"new", "update", "data", "community"}

# One commit may carry several `News:` lines. Tag is optional in [brackets].
NEWS_RE = re.compile(r"^News:\s*(?:\[(?P<tag>[a-zA-Z]+)\]\s*)?(?P<rest>.+?)\s*$",
                     re.MULTILINE)
# Record separators chosen to not collide with commit text.
REC, FLD = "\x1e", "\x1f"


def load_manual():
    try:
        with open(MANUAL, "r", encoding="utf-8") as fh:
            return (json.load(fh) or {}).get("items", [])
    except (OSError, ValueError):
        return []


def git_entries():
    """Parse `News:` trailers from commit messages reachable from HEAD."""
    try:
        out = subprocess.run(
            ["git", "-C", ROOT, "log", f"--pretty=format:%h{FLD}%ad{FLD}%B{REC}",
             "--date=short"],
            capture_output=True, text=True, check=True, timeout=30).stdout
    except (subprocess.SubprocessError, FileNotFoundError):
        print("  (git unavailable — using manual entries only)", file=sys.stderr)
        return []

    items = []
    for raw in out.split(REC):
        raw = raw.strip("\n")
        if not raw or FLD not in raw:
            continue
        short, date, body = raw.split(FLD, 2)
        for m in NEWS_RE.finditer(body):
            parts = [p.strip() for p in m.group("rest").split("|")]
            title = parts[0] if parts else ""
            if not title:
                continue
            tag = (m.group("tag") or "update").lower()
            if tag not in VALID_TAGS:
                tag = "update"
            item = {"date": date, "tag": tag, "title": title,
                    "body": parts[1] if len(parts) > 1 else "",
                    "commit": short}
            link = parts[2] if len(parts) > 2 else ""
            if link:
                item["link"] = link
            items.append(item)
    return items


def main():
    manual = load_manual()
    derived = git_entries()

    # Dedupe: manual entries win over a git entry with the same title (lets you
    # hand-polish a post that also has a trailer). Git entries dedupe by commit.
    seen_titles = {i.get("title", "").strip().lower() for i in manual}
    merged = list(manual)
    for it in derived:
        if it["title"].strip().lower() in seen_titles:
            continue
        seen_titles.add(it["title"].strip().lower())
        merged.append(it)

    # Newest first; stable so same-date ties keep insertion order.
    merged.sort(key=lambda i: i.get("date", ""), reverse=True)
    merged = merged[:MAX_ITEMS]

    payload = {
        "_comment": ("GENERATED by scripts/build_news.py — do not edit by hand. "
                     "Curated posts live in assets/news_manual.json; feature "
                     "posts come from `News:` commit trailers."),
        "items": merged,
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    n_git = sum(1 for i in merged if "commit" in i)
    print(f"Wrote {OUT}: {len(merged)} items "
          f"({len(manual)} manual, {n_git} from commit trailers).")


if __name__ == "__main__":
    main()
