#!/usr/bin/env python3
"""Reconstruct the version history from git into assets/changelog.json, shown as
"Version history" on the Downloads page.

Every release bumps assets/version.json (see the versioning convention). This walks
the commits that changed that file and pairs each version with the commit that best
describes it: for a version touched by several commits (e.g. a revert or a no-bump
bookkeeping edit), the most recent real change wins over a "version:"/"Revert" note.

Output: {"_meta": {...}, "versions": [{"version","date","summary"}...]} newest first.

Standard library + git. Run: python3 scripts/build_changelog.py
"""
import json, os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "changelog.json")
_VER = re.compile(r"\d+\.\d+")
_NOISE = re.compile(r"^(version:|Revert\b)", re.I)


def _run(args):
    return subprocess.run(["git", "-C", ROOT, *args], capture_output=True,
                          text=True, check=True, timeout=30).stdout


def build():
    hashes = _run(["log", "--format=%H", "--", "assets/version.json"]).split()
    # newest-first list of (version, date, subject) for each version.json change
    seen_order = []
    for h in hashes:
        try:
            blob = _run(["show", f"{h}:assets/version.json"])
        except subprocess.SubprocessError:
            continue
        m = _VER.search(blob)
        if not m:
            continue
        date = _run(["show", "-s", "--format=%ad", "--date=short", h]).strip()
        subj = _run(["show", "-s", "--format=%s", h]).strip()
        seen_order.append((m.group(0), date, subj))

    # Group by version; prefer the newest non-bookkeeping subject (list is newest-first).
    chosen = {}
    for ver, date, subj in seen_order:
        cur = chosen.get(ver)
        is_noise = bool(_NOISE.match(subj))
        if cur is None:
            chosen[ver] = (date, subj, is_noise)
        elif cur[2] and not is_noise:      # replace a bookkeeping note with a real change
            chosen[ver] = (date, subj, is_noise)

    def key(v):
        a, b = v.split(".")
        return (int(a), int(b))

    versions = [{"version": v, "date": chosen[v][0], "summary": chosen[v][1]}
                for v in sorted(chosen, key=key, reverse=True)]
    payload = {"_meta": {"note": "GENERATED by scripts/build_changelog.py from git.",
                         "count": len(versions)},
               "versions": versions}
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)
    print(f"  wrote changelog.json: {len(versions)} versions "
          f"(v{versions[-1]['version']} … v{versions[0]['version']})")


if __name__ == "__main__":
    build()
