#!/usr/bin/env python3
"""Generate the AI-curation layer with Claude -> assets/ai_curation.json.

This is the *third* curation layer (alongside official dictyBase curation and
user-submitted "curated-here"). Output is always badged "AI" in the UI and is
explicitly machine-generated, unreviewed, and possibly wrong — the badge + the
front-end filter let users hide it.

Usage:
    export ANTHROPIC_API_KEY=sk-ant-...
    python3 scripts/generate_ai_curation.py cln5 rasG mhcA   # specific genes
    python3 scripts/generate_ai_curation.py --curated        # all curated genes in app.js

Requires:  pip install anthropic
The result is keyed by lowercase gene symbol:
    { "<symbol>": { "summary": str, "go": [[GO id, "P"|"F"|"C", term name], ...] } }
"""
import argparse
import json
import pathlib
import sys
from typing import List, Literal

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "ai_curation.json"
MODEL = "claude-opus-4-8"

SYSTEM = (
    "You are an expert Dictyostelium discoideum molecular biologist helping draft "
    "AI-suggested gene annotations for a model-organism database. Your output is "
    "labelled as AI-generated and is a starting point for human curators — accuracy "
    "matters more than coverage. Only state things you are confident are correct."
)

PROMPT = """For the Dictyostelium discoideum gene **{symbol}**, produce:

1. summary: 2-3 sentence functional summary suitable for a gene record.
2. go: a SHORT list (2-4) of high-confidence Gene Ontology annotations. Use only
   REAL, well-established GO ids you are confident apply to this gene. For each give
   the GO id (GO:NNNNNNN), aspect (P=biological process, F=molecular function,
   C=cellular component), and the official term name. If you are not confident a GO
   id is correct, omit it — do NOT invent ids or pad the list.

Be conservative and factual."""


def pydantic_schema():
    from pydantic import BaseModel

    class GOAnnotation(BaseModel):
        id: str            # GO:NNNNNNN
        aspect: Literal["P", "F", "C"]
        name: str

    class GeneCuration(BaseModel):
        summary: str
        go: List[GOAnnotation]

    return GeneCuration


def curated_symbols() -> List[str]:
    """Pull the curated gene symbols seeded in app.js (best-effort regex)."""
    import re
    txt = (ROOT / "app.js").read_text(encoding="utf-8")
    block = txt[: txt.find("const researchResources")]  # genes are defined before this
    return list(dict.fromkeys(re.findall(r'symbol:\s*"([^"]+)"', block)))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("symbols", nargs="*", help="gene symbols to curate")
    ap.add_argument("--curated", action="store_true", help="use the curated genes from app.js")
    args = ap.parse_args()

    symbols = args.symbols
    if args.curated:
        symbols = curated_symbols()
    if not symbols:
        ap.error("give gene symbols or --curated")

    import anthropic

    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY
    GeneCuration = pydantic_schema()

    data = {}
    if OUT.exists():
        data = json.loads(OUT.read_text(encoding="utf-8"))

    for symbol in symbols:
        print(f"  curating {symbol} ...", file=sys.stderr)
        resp = client.messages.parse(
            model=MODEL,
            max_tokens=2000,
            thinking={"type": "adaptive"},
            system=SYSTEM,
            messages=[{"role": "user", "content": PROMPT.format(symbol=symbol)}],
            output_format=GeneCuration,
        )
        c = resp.parsed_output
        data[symbol.lower()] = {
            "summary": c.summary.strip(),
            "go": [[g.id, g.aspect, g.name] for g in c.go],
        }

    data["_meta"] = {
        "layer": "AI curation",
        "model": MODEL,
        "disclaimer": "Machine-generated by an LLM. Suggestions only — unreviewed, "
        "may be incomplete or wrong. Verify against curated evidence.",
        "schema": "keyed by lowercase gene symbol -> { summary, go: [[GO id, P|F|C, name], ...] }",
    }
    OUT.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len([k for k in data if not k.startswith('_')])} genes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
